repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.192'
  hooks:
  - id: ruff
    # Respect `exclude` and `extend-exclude` settings.
    args: ["--force-exclude"]
- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    entry: "pdm run pytest tests/"
    language: system
    pass_filenames: false
    always_run: true
