repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.4.4'
  hooks:
  - id: ruff
    args: ["--fix"]
  - id: ruff-format
- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    entry: "pdm run pytest tests/"
    language: system
    pass_filenames: false
    always_run: true
- repo: https://github.com/pdm-project/pdm
  rev: 2.15.2
  hooks:
  - id: pdm-export
    # command arguments, e.g.:
    args: ['-o', 'upper-constraints.txt', '--without-hashes']
    files: ^pdm.lock$
