apiVersion: v1
kind: Secret
metadata:
  name: ironic-bmc-secret
  annotations:
    cloud.sap/inject-secrets: "true"
type: Opaque
data:
  ipmi_user_name: {{ printf "vault+kvv2:///secrets/%s/ironic/impi-user/ironic/username" .Values.region | b64enc }}
  ipmi_user_passwd: {{ printf "vault+kvv2:///secrets/%s/ironic/impi-user/ironic/password" .Values.region | b64enc }}

